"""Typed contracts exchanged between pipeline stages.

Agents communicate exclusively through these types plus the run blackboard —
never through a shared conversation history. That is the difference between an
architecture that degrades at stage 8 and one that does not.
"""

from ads.contracts.base import Artifact, ArtifactType, FrozenModel
from ads.contracts.comprehension import (
    ComprehensionBrief,
    ComprehensionScope,
    InterpretationBatchProposal,
    InterpretationItem,
    InterpretationKind,
    InterpretationProposal,
    ModelConfidence,
    VerificationQuestion,
)
from ads.contracts.datacard import (
    ColumnProfile,
    DataCard,
    DatetimeStats,
    LoadIssue,
    NumericStats,
    SemanticType,
    Sensitivity,
    TextScript,
    TextStats,
    ValueCount,
)
from ads.contracts.evidence import (
    MeasurementBundle,
    MeasurementKind,
    MeasurementRecord,
    SubjectRef,
)
from ads.contracts.gates import (
    BUILTIN_PROFILES,
    DEFAULT_PROFILE,
    AutonomyProfile,
    CritiqueResult,
    DecisionOption,
    Finding,
    GateDecision,
    GateVerdict,
    HumanPrompt,
    PermissionTier,
    QualitySignals,
    RiskClass,
    Severity,
)
from ads.contracts.integration import (
    AggregationStep,
    Cardinality,
    IntegrationPlan,
    IntegrationPlanProposal,
    JoinStep,
    KeyCandidate,
    RelationshipCandidate,
    RowsPerParentStats,
)
from ads.contracts.leakage import LeakageFinding, LeakageKind, LeakageReport
from ads.contracts.problem import (
    METRICS_BY_TASK,
    SUPERVISED_TASKS,
    Metric,
    ProblemCandidate,
    ProblemCandidateProposal,
    ProblemCandidateSet,
    ProblemDefinition,
    ProblemDiscoveryProposal,
    ProblemSupport,
    TaskType,
)
from ads.contracts.validation import (
    IdentifierContainmentSignal,
    RepeatedEntitySignal,
    SplitStrategy,
    TemporalSpanSignal,
    ValidationSignals,
    ValidationStrategy,
    ValidationStrategyProposal,
)

__all__ = [
    "AggregationStep",
    "Artifact",
    "ArtifactType",
    "AutonomyProfile",
    "BUILTIN_PROFILES",
    "Cardinality",
    "ColumnProfile",
    "CritiqueResult",
    "DataCard",
    "DatetimeStats",
    "DecisionOption",
    "DEFAULT_PROFILE",
    "Finding",
    "FrozenModel",
    "GateDecision",
    "GateVerdict",
    "HumanPrompt",
    "IntegrationPlan",
    "IntegrationPlanProposal",
    "IdentifierContainmentSignal",
    "JoinStep",
    "KeyCandidate",
    "LeakageFinding",
    "LeakageKind",
    "LeakageReport",
    "LoadIssue",
    "Metric",
    "METRICS_BY_TASK",
    "NumericStats",
    "PermissionTier",
    "ProblemCandidate",
    "ProblemCandidateProposal",
    "ProblemCandidateSet",
    "ProblemDefinition",
    "ProblemDiscoveryProposal",
    "ProblemSupport",
    "QualitySignals",
    "RelationshipCandidate",
    "RowsPerParentStats",
    "RepeatedEntitySignal",
    "RiskClass",
    "SemanticType",
    "Sensitivity",
    "Severity",
    "SplitStrategy",
    "SUPERVISED_TASKS",
    "TaskType",
    "TemporalSpanSignal",
    "ValidationSignals",
    "ValidationStrategy",
    "ValidationStrategyProposal",
    "ValueCount",
    "ComprehensionBrief",
    "ComprehensionScope",
    "InterpretationBatchProposal",
    "InterpretationItem",
    "InterpretationKind",
    "InterpretationProposal",
    "MeasurementBundle",
    "MeasurementKind",
    "MeasurementRecord",
    "ModelConfidence",
    "SubjectRef",
    "TextScript",
    "TextStats",
    "VerificationQuestion",
]
