"""Write the control-plane credential to a local, gitignored env file.

    python scripts/set_password.py --username isobed18

Prompts for the password, hashes it with scrypt, and writes `.auth.env` next to
the repository root. The plaintext is never written anywhere and never enters
the repository -- only the hash does, and only into a gitignored file.

Pass --password to supply it non-interactively. That leaves the password in
shell history, so prefer the prompt unless you are scripting.
"""

from __future__ import annotations

import argparse
import getpass
import secrets
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from ads.api.auth import hash_password  # noqa: E402

ENV_PATH = Path(__file__).resolve().parent.parent / ".auth.env"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--username", required=True)
    parser.add_argument(
        "--password",
        help="Skip the prompt. Ends up in shell history; use the prompt when you can.",
    )
    parser.add_argument(
        "--session-hours",
        type=float,
        default=12.0,
        help="How long a login lasts before it must be repeated (default: 12).",
    )
    args = parser.parse_args()

    password = args.password
    if not password:
        password = getpass.getpass("Parola: ")
        if password != getpass.getpass("Parola (tekrar): "):
            raise SystemExit("Parolalar eşleşmedi.")
    if not password:
        raise SystemExit("Boş parola kabul edilmiyor.")

    # Rotating the signing secret alongside the password invalidates every
    # session issued under the old one, which is what a password change should
    # mean.
    secret = secrets.token_urlsafe(32)

    ENV_PATH.write_text(
        "\n".join(
            [
                "# Control-plane credential. Generated by scripts/set_password.py.",
                "# Gitignored on purpose: the hash is not a secret you want published,",
                "# and the signing secret genuinely is one.",
                f"ADS_AUTH_USERNAME={args.username}",
                f"ADS_AUTH_PASSWORD_HASH={hash_password(password)}",
                f"ADS_AUTH_SECRET={secret}",
                f"ADS_AUTH_SESSION_HOURS={args.session_hours}",
                "",
            ]
        ),
        encoding="utf-8",
    )

    print(f"Yazıldı: {ENV_PATH}")
    print(f"Kullanıcı: {args.username}")
    print("Parola saklanmadı; yalnızca scrypt özeti yazıldı.")
    print("Mevcut oturumlar geçersiz kılındı (imza anahtarı yenilendi).")


if __name__ == "__main__":
    main()
