"""Replace the public control-plane accounts with generated credentials.

Usage:
    python scripts/set_users.py gonenc-ads berkin-ads emre-ads ishak-ads

Each password is printed once and only its scrypt hash is written to the
gitignored ``.auth.env`` file. Replacing the file removes every account not
named on the command line and rotates the session secret.
"""

from __future__ import annotations

import argparse
import json
import secrets
import string
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from ads.api.auth import hash_password  # noqa: E402

ENV_PATH = ROOT / ".auth.env"
_ALPHABET = string.ascii_letters + string.digits


def generated_password(username: str) -> str:
    suffix = "".join(secrets.choice(_ALPHABET) for _ in range(12))
    return f"admin-{username}-{suffix}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("usernames", nargs="+", help="Complete replacement account list")
    parser.add_argument("--session-hours", type=float, default=12.0)
    args = parser.parse_args()
    usernames = list(dict.fromkeys(name.strip() for name in args.usernames if name.strip()))
    if not usernames:
        raise SystemExit("At least one non-empty username is required.")

    passwords = {username: generated_password(username) for username in usernames}
    hashes = {username: hash_password(password) for username, password in passwords.items()}
    payload = json.dumps(hashes, ensure_ascii=True, separators=(",", ":"))
    ENV_PATH.write_text(
        "\n".join(
            [
                "# Control-plane accounts. Generated by scripts/set_users.py.",
                "# Plaintext passwords are printed once and are never stored.",
                f"ADS_AUTH_USERS_JSON={payload}",
                f"ADS_AUTH_SECRET={secrets.token_urlsafe(32)}",
                f"ADS_AUTH_SESSION_HOURS={args.session_hours}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(usernames)} accounts to {ENV_PATH}")
    for username, password in passwords.items():
        print(f"{username}\t{password}")
    print("All previous accounts and sessions are invalid now.")


if __name__ == "__main__":
    main()
